import React, { useEffect, useState } from "react";
import { Card, CardContent, Typography, Divider } from "@mui/material";
import { loadLogs } from "../services/storage";

export default function LogConsole() {
  const [logs, setLogs] = useState([]);

  useEffect(() => {
    const read = () => setLogs(loadLogs());
    read();
    const i = setInterval(read, 800); // lightweight “live” console
    return () => clearInterval(i);
  }, []);

  return (
    <Card>
      <CardContent>
        <Typography variant="h6" gutterBottom>Client Logging (assessment requirement)</Typography>
        <Typography variant="caption" color="text.secondary">
          Showing recent events generated by the app (also in browser console).
        </Typography>
        <Divider sx={{ my: 1 }} />
        <pre style={{ margin: 0, whiteSpace: "pre-wrap", fontFamily: "ui-monospace" }}>
          {logs.map((l, i) => `[${l.t}] ${l.type} - ${l.msg}${l.meta ? " " + JSON.stringify(l.meta) : ""}`).join("\n")}
        </pre>
      </CardContent>
    </Card>
  );
}
